services:
  swiss-datashare:
    build: .
    restart: unless-stopped
    ports:
      - 3005:3000
    environment:
      - TRUST_PROXY=false
    volumes:
      - "./data:/opt/app/backend/data:Z"
      - "./data/images:/opt/app/frontend/public/img:Z"
#      - "./config.yaml:/opt/app/config.yaml"